apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trading
  template:
    metadata:
      labels:
        app: trading
    spec:
      containers:
        - name: frontend
          image: frontend-image:latest
          ports:
            - containerPort: 3000
        - name: backend
          image: backend-image:latest
          ports:
            - containerPort: 5000
